# Generated by Django 4.2.5 on 2023-10-17 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Aplicacion1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntajetotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='puntaje total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='preguntasrespondidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='es esta la respuesta correcta?')),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Puntaje')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.preguntas')),
                ('respuestas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Aplicacion1.respuestas')),
            ],
        ),
    ]
