# Generated by Django 4.2.5 on 2023-10-17 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0002_usuario_preguntasrespondidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.usuario'),
        ),
    ]
