# Generated by Django 4.2.5 on 2023-11-12 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0003_preguntasrespondidas_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuestas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Aplicacion1.respuestas'),
        ),
    ]
