# Generated by Django 4.2.5 on 2023-11-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0004_alter_preguntasrespondidas_respuestas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='Aplicacion1.usuario'),
        ),
        migrations.AlterField(
            model_name='respuestas',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='Aplicacion1.preguntas'),
        ),
    ]
