# Generated by Django 4.2.5 on 2023-11-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0005_alter_preguntasrespondidas_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizuser',
        ),
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='respuestas',
        ),
        migrations.AddField(
            model_name='preguntas',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Aplicacion1.respuestas'),
        ),
    ]
