# Generated by Django 4.2.5 on 2023-11-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0006_rename_usuario_preguntasrespondidas_quizuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='quizuser',
            new_name='usuario',
        ),
    ]
