# Generated by Django 4.2.5 on 2023-11-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0008_rename_usuario_preguntasrespondidas_quizuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='puntajetotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='puntaje total'),
        ),
    ]
