# Generated by Django 4.2.5 on 2023-11-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0011_remove_preguntasrespondidas_retroalimentacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='correcta',
            field=models.BooleanField(default=False, verbose_name='es correcta'),
        ),
    ]
