# Generated by Django 4.2.5 on 2023-11-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0012_alter_preguntasrespondidas_correcta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preguntas',
            name='retroalimentacion',
            field=models.TextField(blank=True, verbose_name='Retroalimentacion'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6, verbose_name='Puntaje'),
        ),
    ]
