# Generated by Django 4.2.5 on 2023-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0013_alter_preguntas_retroalimentacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='pregunta_imagenes/', verbose_name='Imagen de la pregunta'),
        ),
    ]
