# Generated by Django 4.2.7 on 2023-11-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0017_remove_userprofile_bio_remove_userprofile_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth_date'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, max_length=40, verbose_name='gender'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
