# Generated by Django 4.2.7 on 2023-11-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0018_usuario_birth_date_usuario_gender_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Cumpleaños'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, max_length=40, verbose_name='Genero'),
        ),
    ]
