# Generated by Django 4.2.5 on 2023-11-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion1', '0019_alter_usuario_birth_date_alter_usuario_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Genero'),
        ),
    ]
